[package]
name = "pharma-supply-chain"
version = "0.1.0"
edition = "2018"

[dependencies]
substreams = "0.1"
substreams-ethereum = "0.1"
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }
