[package]
name = "substreams_project"
version = "0.1.0"
edition = "2018"

[dependencies]
substreams = "0.1.1"
substreams-ethereum = "0.1.1"
prost = "0.8"
prost-types = "0.8"

[build-dependencies]
prost-build = "0.8"
